/*
 * This file was automatically generated by EvoSuite
 * Wed Mar 26 13:04:37 GMT 2025
 */

package org.apache.commons.lang3.text.translate;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.lang3.text.translate.JavaUnicodeEscaper;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class JavaUnicodeEscaper_ESTest extends JavaUnicodeEscaper_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      JavaUnicodeEscaper javaUnicodeEscaper0 = JavaUnicodeEscaper.between(0, 970);
      assertNotNull(javaUnicodeEscaper0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      JavaUnicodeEscaper javaUnicodeEscaper0 = JavaUnicodeEscaper.above(0);
      // Undeclared exception!
      try { 
        javaUnicodeEscaper0.toUtf16Escape(0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 1 out of bounds for length 1
         //
         verifyException("org.apache.commons.lang3.text.translate.JavaUnicodeEscaper", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      JavaUnicodeEscaper javaUnicodeEscaper0 = JavaUnicodeEscaper.outsideOf((-398), (-398));
      assertNotNull(javaUnicodeEscaper0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      JavaUnicodeEscaper javaUnicodeEscaper0 = new JavaUnicodeEscaper(9, 970, false);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      JavaUnicodeEscaper javaUnicodeEscaper0 = JavaUnicodeEscaper.above((-1));
      // Undeclared exception!
      try { 
        javaUnicodeEscaper0.toUtf16Escape((-1));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Not a valid Unicode code point: 0xFFFFFFFF
         //
         verifyException("java.lang.Character", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      JavaUnicodeEscaper javaUnicodeEscaper0 = JavaUnicodeEscaper.below(65538);
      String string0 = javaUnicodeEscaper0.toUtf16Escape(65538);
      assertEquals("\\uD800\\uDC02", string0);
  }
}
