/*
 * This file was automatically generated by EvoSuite
 * Wed Mar 26 13:07:09 GMT 2025
 */

package org.apache.commons.lang3.text.translate;

import org.junit.Test;
import static org.junit.Assert.*;
import java.io.StringWriter;
import java.io.Writer;
import org.apache.commons.lang3.text.translate.UnicodeUnpairedSurrogateRemover;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class UnicodeUnpairedSurrogateRemover_ESTest extends UnicodeUnpairedSurrogateRemover_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      UnicodeUnpairedSurrogateRemover unicodeUnpairedSurrogateRemover0 = new UnicodeUnpairedSurrogateRemover();
      StringWriter stringWriter0 = new StringWriter();
      boolean boolean0 = unicodeUnpairedSurrogateRemover0.translate(55296, (Writer) stringWriter0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      UnicodeUnpairedSurrogateRemover unicodeUnpairedSurrogateRemover0 = new UnicodeUnpairedSurrogateRemover();
      StringWriter stringWriter0 = new StringWriter();
      stringWriter0.write((-1406));
      StringBuffer stringBuffer0 = stringWriter0.getBuffer();
      unicodeUnpairedSurrogateRemover0.translate((CharSequence) stringBuffer0, (Writer) stringWriter0);
      assertEquals(2, stringBuffer0.length());
      assertEquals("\uFA82\uFA82", stringWriter0.toString());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      UnicodeUnpairedSurrogateRemover unicodeUnpairedSurrogateRemover0 = new UnicodeUnpairedSurrogateRemover();
      StringWriter stringWriter0 = new StringWriter();
      boolean boolean0 = unicodeUnpairedSurrogateRemover0.translate(57343, (Writer) stringWriter0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      UnicodeUnpairedSurrogateRemover unicodeUnpairedSurrogateRemover0 = new UnicodeUnpairedSurrogateRemover();
      StringWriter stringWriter0 = new StringWriter();
      boolean boolean0 = unicodeUnpairedSurrogateRemover0.translate((-1318), (Writer) stringWriter0);
      assertFalse(boolean0);
  }
}
