/*
 * This file was automatically generated by EvoSuite
 * Wed Mar 26 13:30:26 GMT 2025
 */

package org.apache.commons.lang3.text;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.text.ChoiceFormat;
import java.text.DateFormat;
import java.text.DateFormatSymbols;
import java.text.DecimalFormat;
import java.text.FieldPosition;
import java.text.Format;
import java.text.MessageFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.ParsePosition;
import java.util.Locale;
import org.apache.commons.lang3.text.CompositeFormat;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.text.MockDateFormat;
import org.evosuite.runtime.mock.java.text.MockSimpleDateFormat;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class CompositeFormat_ESTest extends CompositeFormat_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Locale locale0 = Locale.TAIWAN;
      MockSimpleDateFormat mockSimpleDateFormat0 = new MockSimpleDateFormat("=", locale0);
      DateFormatSymbols dateFormatSymbols0 = DateFormatSymbols.getInstance();
      MockSimpleDateFormat mockSimpleDateFormat1 = new MockSimpleDateFormat("", dateFormatSymbols0);
      CompositeFormat compositeFormat0 = new CompositeFormat(mockSimpleDateFormat0, mockSimpleDateFormat1);
      String string0 = compositeFormat0.reformat("=");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Locale locale0 = Locale.FRANCE;
      MessageFormat messageFormat0 = new MessageFormat("}*KnlZ88gQEkmfM0", locale0);
      CompositeFormat compositeFormat0 = new CompositeFormat(messageFormat0, messageFormat0);
      ParsePosition parsePosition0 = new ParsePosition(0);
      Object object0 = compositeFormat0.parseObject("", parsePosition0);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CompositeFormat compositeFormat0 = new CompositeFormat((Format) null, (Format) null);
      Format format0 = compositeFormat0.getParser();
      assertNull(format0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Locale locale0 = Locale.CANADA;
      NumberFormat numberFormat0 = NumberFormat.getCurrencyInstance(locale0);
      CompositeFormat compositeFormat0 = new CompositeFormat(numberFormat0, (Format) null);
      Format format0 = compositeFormat0.getFormatter();
      assertNull(format0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      MockSimpleDateFormat mockSimpleDateFormat0 = new MockSimpleDateFormat("");
      CompositeFormat compositeFormat0 = new CompositeFormat(mockSimpleDateFormat0, mockSimpleDateFormat0);
      ParsePosition parsePosition0 = new ParsePosition(1);
      Object object0 = compositeFormat0.parseObject("", parsePosition0);
      Format.Field format_Field0 = mock(Format.Field.class, new ViolatedAssumptionAnswer());
      FieldPosition fieldPosition0 = new FieldPosition(format_Field0, 1);
      StringBuffer stringBuffer0 = compositeFormat0.format(object0, (StringBuffer) null, fieldPosition0);
      assertNull(stringBuffer0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Locale locale0 = Locale.PRC;
      MockSimpleDateFormat mockSimpleDateFormat0 = new MockSimpleDateFormat("", locale0);
      CompositeFormat compositeFormat0 = new CompositeFormat(mockSimpleDateFormat0, mockSimpleDateFormat0);
      Integer integer0 = new Integer(0);
      StringBuffer stringBuffer0 = new StringBuffer((CharSequence) "");
      Format.Field format_Field0 = mock(Format.Field.class, new ViolatedAssumptionAnswer());
      FieldPosition fieldPosition0 = new FieldPosition(format_Field0, (-2648));
      StringBuffer stringBuffer1 = compositeFormat0.format((Object) integer0, stringBuffer0, fieldPosition0);
      assertEquals("", stringBuffer1.toString());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      MockSimpleDateFormat mockSimpleDateFormat0 = new MockSimpleDateFormat("");
      CompositeFormat compositeFormat0 = new CompositeFormat(mockSimpleDateFormat0, mockSimpleDateFormat0);
      try { 
        compositeFormat0.reformat("");
        fail("Expecting exception: ParseException");
      
      } catch(ParseException e) {
         //
         // Format.parseObject(String) failed
         //
         verifyException("java.text.Format", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      DecimalFormat decimalFormat0 = new DecimalFormat();
      CompositeFormat compositeFormat0 = new CompositeFormat(decimalFormat0, decimalFormat0);
      // Undeclared exception!
      try { 
        compositeFormat0.reformat((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      MessageFormat messageFormat0 = new MessageFormat("org.apache.commons.lang3.text.CompositeFormat");
      DateFormat dateFormat0 = MockDateFormat.getDateInstance(0);
      CompositeFormat compositeFormat0 = new CompositeFormat(messageFormat0, dateFormat0);
      // Undeclared exception!
      try { 
        compositeFormat0.reformat("org.apache.commons.lang3.text.CompositeFormat");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cannot format given Object as a Date
         //
         verifyException("java.text.DateFormat", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      NumberFormat numberFormat0 = NumberFormat.getPercentInstance();
      CompositeFormat compositeFormat0 = new CompositeFormat(numberFormat0, numberFormat0);
      // Undeclared exception!
      try { 
        compositeFormat0.parseObject("\"zoA[/1Atf5Xu}1", (ParsePosition) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CompositeFormat compositeFormat0 = new CompositeFormat((Format) null, (Format) null);
      FieldPosition fieldPosition0 = new FieldPosition(0);
      // Undeclared exception!
      try { 
        compositeFormat0.format((Object) null, (StringBuffer) null, fieldPosition0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.text.CompositeFormat", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      DecimalFormat decimalFormat0 = new DecimalFormat();
      CompositeFormat compositeFormat0 = new CompositeFormat(decimalFormat0, decimalFormat0);
      // Undeclared exception!
      try { 
        compositeFormat0.format((Object) decimalFormat0, (StringBuffer) null, (FieldPosition) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cannot format given Object as a Number
         //
         verifyException("java.text.DecimalFormat", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Locale locale0 = Locale.SIMPLIFIED_CHINESE;
      MessageFormat messageFormat0 = new MessageFormat("4 hh#", locale0);
      CompositeFormat compositeFormat0 = new CompositeFormat(messageFormat0, messageFormat0);
      // Undeclared exception!
      try { 
        compositeFormat0.format((Object) locale0, (StringBuffer) null, (FieldPosition) null);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // class java.util.Locale cannot be cast to class [Ljava.lang.Object; (java.util.Locale and [Ljava.lang.Object; are in module java.base of loader 'bootstrap')
         //
         verifyException("java.text.MessageFormat", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      ChoiceFormat choiceFormat0 = new ChoiceFormat("^Rk5.T}^bq'");
      CompositeFormat compositeFormat0 = new CompositeFormat(choiceFormat0, choiceFormat0);
      ParsePosition parsePosition0 = new ParsePosition((-1));
      Object object0 = compositeFormat0.parseObject("^Rk5.T}^bq'", parsePosition0);
      Format.Field format_Field0 = mock(Format.Field.class, new ViolatedAssumptionAnswer());
      FieldPosition fieldPosition0 = new FieldPosition(format_Field0, (-1));
      // Undeclared exception!
      try { 
        compositeFormat0.format(object0, (StringBuffer) null, fieldPosition0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 0 out of bounds for length 0
         //
         verifyException("java.text.ChoiceFormat", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      MockSimpleDateFormat mockSimpleDateFormat0 = new MockSimpleDateFormat();
      CompositeFormat compositeFormat0 = new CompositeFormat(mockSimpleDateFormat0, mockSimpleDateFormat0);
      ParsePosition parsePosition0 = new ParsePosition((-1));
      // Undeclared exception!
      try { 
        compositeFormat0.parseObject("5hGn@~[PC40B=RO", parsePosition0);
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      MockSimpleDateFormat mockSimpleDateFormat0 = new MockSimpleDateFormat();
      CompositeFormat compositeFormat0 = new CompositeFormat(mockSimpleDateFormat0, mockSimpleDateFormat0);
      Integer integer0 = new Integer(0);
      StringBuffer stringBuffer0 = new StringBuffer((CharSequence) "");
      Format.Field format_Field0 = mock(Format.Field.class, new ViolatedAssumptionAnswer());
      FieldPosition fieldPosition0 = new FieldPosition(format_Field0, (-2648));
      StringBuffer stringBuffer1 = compositeFormat0.format((Object) integer0, stringBuffer0, fieldPosition0);
      assertEquals(15, stringBuffer1.length());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      DecimalFormat decimalFormat0 = new DecimalFormat();
      CompositeFormat compositeFormat0 = new CompositeFormat(decimalFormat0, decimalFormat0);
      DecimalFormat decimalFormat1 = (DecimalFormat)compositeFormat0.getFormatter();
      assertEquals("#,##0.###", decimalFormat1.toPattern());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Locale locale0 = Locale.ITALY;
      NumberFormat numberFormat0 = NumberFormat.getCurrencyInstance(locale0);
      CompositeFormat compositeFormat0 = new CompositeFormat(numberFormat0, numberFormat0);
      DecimalFormat decimalFormat0 = (DecimalFormat)compositeFormat0.getParser();
      assertEquals("\u00A4 #.##0,00", decimalFormat0.toLocalizedPattern());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Locale locale0 = Locale.TAIWAN;
      MockSimpleDateFormat mockSimpleDateFormat0 = new MockSimpleDateFormat("=", locale0);
      CompositeFormat compositeFormat0 = new CompositeFormat(mockSimpleDateFormat0, mockSimpleDateFormat0);
      String string0 = compositeFormat0.reformat("=");
      assertEquals("=", string0);
  }
}
